# -- Site Configuration --

baseURL = "https://huyixi.com/"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
theme = "blue"

enableRobotsTXT = true
paginate = 30
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh]
    weight = 1
    languageName = "简体中文"

  [languages.en]
    weight = 2
    languageName = "English"