# -- Site Configuration --

baseURL = "https://huyixi.com/"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
theme = "blue"
enableGitInfo = true

enableRobotsTXT = true
paginate = 30
summaryLength = 0

[avatar]
  avatarImage = "img/avatar.jpg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh]
    weight = 1
    languageName = "简体中文"
    dateFormat = "2006 年 01 月 02 日"


  [languages.en]
    weight = 2
    languageName = "English"
    dateFormat = "January 2, 2006"