[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [main.params]
    icon = "house-solid"
    showName = false

[[main]]
  name = "Project"
  pageRef = "projects"
  weight = 10
  [main.params]
    icon = "app-store-ios"
    showName = false

[[main]]
  name = "Like"
  pageRef = "likes"
  weight = 20
  [main.params]
    icon = "heart-solid"
    showName = false

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
