[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [main.params]
    icon = "house-solid"
    tooltip = "My Posts"

[[main]]
  name = "Project"
  pageRef = "project"
  weight = 10
  [main.params]
    icon = "app-store-ios"
    tooltip = "My Creation"

[[main]]
  name = "Like"
  pageRef = "like"
  weight = 20
  [main.params]
    icon = "heart-solid"
    tooltip = "My Favorites"
