defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
fingerprintAlgorithm = "sha256"

[header]
  layout = "basic"
  logo = "img/logo.png"
  logoDark = "img/dark-logo.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showAppearanceSwitcher = false

[homepage]
  layout = "page" 
  showRecent = true
  recentLimit = 10

[author]
  authorImage = "img/avatar.jpg"

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = false
  showMore = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = true
  showWordCount = true
  showComments = false
  # sharingLinks = [ "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]

[list]
  showSummary = true
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
