baseURL = 'http://huyixi.com/'
languageCode = 'en'
title = 'huyixi'
description = 'Personal_Website'
theme = 'hugo-book'
[params]
  BookTheme = 'dark'
  BookToC = 'true'
  BookSection = 'wiki'
  icon = "/images/rss.png"
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "index"
isPlainText = false