name: Sync NeoDB Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

env:
  CATEGORIES: 'book,movie,music,podcast'  # 类别列表，用逗号分隔

jobs:
  neodb:
    name: Sync NeoDB Data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check JQ
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq is not installed. Installing..."
          sudo apt-get update
          sudo apt-get install -y jq
        else
          echo "jq is already installed."
        fi
        echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Get Current Count
      run: |
        CURRENT_COUNT() {
          jq '.count' data/neodb/neodb.json
        }
            COUNT=$(CURRENT_COUNT)
        echo "CURRENT_COUNT=$COUNT"
        echo "CURRENT_COUNT=$COUNT" >> $GITHUB_ENV

    - name: Get NeoDB JSON and Count
      run: |
        download_and_count() {
          category=$1
          echo "Downloading data for category: $category"
          curl -X 'GET' \
          "https://neodb.social/api/me/shelf/complete?category=$category&page=1" \
          -H 'accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.NEODB_ACCESS_TOKEN }}' > "${category}1.json"

          # 计算并打印每个类别的计数
          count=$(jq '.count' "${category}1.json")
          echo "${category} count: $count"

          REMOTE_COUNT=$((REMOTE_COUNT + count))
        }

        # 遍历每个类别
        REMOTE_COUNT=0
        IFS=',' read -r -a categories <<< "${{ env.CATEGORIES }}"
        for category in "${categories[@]}"; do
          download_and_count "$category"
        done

        echo "REMOTE_COUNT=$REMOTE_COUNT"
        echo "REMOTE_COUNT=$REMOTE_COUNT" >> $GITHUB_ENV

    - name: Count Compare
      run: |
        if [ "${{ env.REMOTE_COUNT }}" = "${{ env.CURRENT_COUNT }}" ]; then
          echo "Variables are equal. Skipping the next steps."
          exit 0
        else
          echo "Variables are not equal. Running the next steps."
        fi

    - name: Get All NeoDB Data
      run: |
        mkdir -p neodb
        cd neodb
        IFS=',' read -r -a categories <<< "${{ env.CATEGORIES }}"
        for category in "${categories[@]}"; do
          # Extract the value of the pages field from JSON
          pages=$(jq '.pages' "../${category}1.json")
          for ((i=1; i<=$pages; i++)); do
            url="https://neodb.social/api/me/shelf/complete?category=$category&page=$i"
            filename="${category}$i.json"
            curl -X 'GET' "$url" -H 'accept: application/json' \
            -H 'Authorization: Bearer ${{ secrets.NEODB_ACCESS_TOKEN }}' > "$filename"
          done
        done
        # Combine all data into one file
        jq -c -s '{data: map(.data[]) | unique | sort_by(.created_time) | reverse, pages: map(.pages)[0], count: map(.count)[0]}' *.json > neodb.json
        cp -f neodb.json "${{ env.WORK_DIR }}/data/neodb/"

    - name: Download NeoDB Cover
      run: |
        json=$(cat data/neodb/neodb.json)
        image_urls=$(echo "$json" | jq -r '.data[] | "\(.item.category)|\(.item.cover_image_url)"')
        for entry in $image_urls; do
          category=$(echo $entry | cut -d'|' -f1)
          url=$(echo $entry | cut -d'|' -f2)

          if [ -z "$url" ] || [[ "$url" == "null" ]]; then
            echo "Invalid URL for category $category, skipping..."
            continue
          fi

          if [ ! -d "data/neodb/cover/$category" ]; then
            mkdir -p "data/neodb/cover/$category"
          fi

          filename=$(basename "$url")
          filepath="data/neodb/cover/$category/$filename"
          if [ ! -f "$filepath" ]; then
            curl -o "$filepath" "$url"
            echo "Downloaded $filepath"
          fi
        done

    - name: Upload Cover Images as Artifact
      if: always() 
      uses: actions/upload-artifact@v2
      with:
        name: cover-images 
        path: data/neodb/cover/

    - name: Git Add and Commit
      if: ${{ env.REMOTE_COUNT != env.CURRENT_COUNT }}
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore(data): update neodb data'
        add: './data/neodb'

    - name: Build Hugo and Deploy
          if: ${{ env.REMOTE_COUNT != env.CURRENT_COUNT }}
          uses: peter-evans/repository-dispatch@v2
          with:
              event-type: "Build Hugo and Deploy"
